import type { Metadata } from 'next';
import { Mulish } from 'next/font/google';
import './globals.css';
import { AppThemeProvider } from '@/context';
import { AppDrawer, AppFooter } from '@/components';
import Box from '@mui/material/Box';
import ReactQueryProvider from '@/components/reactQuery/ReactQueryProvider';
import 'react-toastify/dist/ReactToastify.css';
import { ToastContainer, toast } from 'react-toastify';
import AuthProvider from '@/Security/AuthProvider';
import { Suspense } from 'react';
import Loading from './loading';
const inter = Mulish({ weight: '600', subsets: ['latin'], display: 'swap' });

export const metadata: Metadata = {
  title: 'Home',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang='en' className={inter.className}>
      <body>
        <AuthProvider>
          <ReactQueryProvider>
            <AppThemeProvider>
              <AppDrawer />
              <Suspense fallback={<Loading />}>
                <Box padding={'1rem 1rem'}>{children}</Box>
              </Suspense>
              <AppFooter />
              <ToastContainer />
            </AppThemeProvider>
          </ReactQueryProvider>
        </AuthProvider>
      </body>
    </html>
  );
}
